package com.onlineShopping.Web.enums;

public enum Status {
    PENDING,

    PAYMENT_APPROVED,

    PAYMENT_FAILED,
    AWAITING_PAYMENT,
    AWAITING_FULFILLMENT,
    AWAITING_SHIPMENT,
    AWAITING_PICKUP,
    PARTIALLY_SHIPPED,
    COMPLETED_SHIPPED,
    CANCELLED_DECLINED,
    REFUNDED_DISPUTED,
    MANUAL_VERIFICATION_REQUIRED,
    PARTIALLY_REFUNDED
}


